PFD Challenge 1/Models/FundTransferReview.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PFD_Challenge_1.Models
{
    public class FundTransferReview
    {
        [Display(Name = "Recipient")]
        [Required]
        public string Recipient { get; set; }
        [Display(Name = "Balance")]
        [Required]
        public decimal Balance { get; set; }
        [Display(Name = "Transfer Amount")]
        [Required]
        public decimal TransferAmount { get; set; }
        [Display(Name = "Future Transfer")]
        [Required]
        public string FutureTransfer { get; set; }
        [Display(Name = "Planned time of transfer")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MMM-dd}")]
        public DateTime? TimeTransfer { get; set; }
    }
}

PFD Challenge 1/Controllers/FundTransferController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PFD_Challenge_1.DAL;
using PFD_Challenge_1.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.Text.RegularExpressions;
using System.Net.Http;
using PFD_Challenge_1.TelegramModel;
using Newtonsoft.Json;
using System.Text;
using System.Net.Mail;
using JsonSerializer = System.Text.Json.JsonSerializer;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace PFD_Challenge_1.Controllers
{
    public class FundTransferController : Controller
    {
        BankAccountDAL bankAccountContext = new BankAccountDAL();
        BankUserDAL bankUserContext = new BankUserDAL();
        FutureTransferDAL futureTransferContext = new FutureTransferDAL();
        TransactionDAL transactionContext = new TransactionDAL();
        public IActionResult FundTransfer()
        {
            if (HttpContext.Session.GetString("NRIC") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            BankAccount ba = bankAccountContext.GetBankAccount(HttpContext.Session.GetString("NRIC"));
            if (ba == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Transaction t = transactionContext.GetLatestTransaction(ba.AccNo);
            FundTransferVM ft = new FundTransferVM
            {
                account = ba,
                transactions = t,
            };
            BankUser bu = bankUserContext.GetBankUser(ba.Nric);

            ViewData["User"] = bu.Name;
            return View(ft);
        }
        public async Task<ActionResult> FundTransferReview()
        {
            BankAccount ba;
            FundTransferReview ftr;
            //Check if there are existing transactions left in the restdb
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://ocbcdatabase-0c55.restdb.io");
            client.DefaultRequestHeaders.Add("x-api-key", "61f2742d7e55272295017175");
            HttpResponseMessage response = await client.GetAsync("/rest/temptransac");
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                if(data != null)
                {
                    List<TempTransac> tempTransacList = JsonConvert.DeserializeObject<List<TempTransac>>(data);
                    foreach(TempTransac tempTransac in tempTransacList)
                    {
                        if (HttpContext.Session.GetString("NRIC") == tempTransac.Nric)
                        {
                            //Get bank Account details
                            ba = bankAccountContext.GetBankAccount(HttpContext.Session.GetString("NRIC"));
                            if (ba == null)
                            {
                                return RedirectToAction("Index", "Home");
                            }
                            ftr = new FundTransferReview
                            {
                                Recipient = tempTransac.Recipient,
                                Balance = ba.Balance,
                                TransferAmount = tempTransac.Amount,
                                FutureTransfer = "false",
                            };
                            HttpResponseMessage deleteResponse = await client.DeleteAsync("/rest/temptransac/"+tempTransac._id);
                            if (transactionContext.GetTransaction(tempTransac.TransacID) != null)
                            {
                                transactionContext.DeleteTransactionRecord(tempTransac.TransacID);
                            }
                            return View(ftr);
                        }
                        else
                        {
                            //Get bank Account details
                           ba = bankAccountContext.GetBankAccount(HttpContext.Session.GetString("NRIC"));
                            if (ba == null)
                            {
                                return RedirectToAction("Index", "Home");
                            }
                            ftr = new FundTransferReview
                            {
                                Balance = ba.Balance,
                                FutureTransfer = "false",
                            };
                            return View(ftr);
                        }
                    }
                }
            }
            //Get bank Account details
            ba = bankAccountContext.GetBankAccount(HttpContext.Session.GetString("NRIC"));
            if (ba == null)
            {
                return RedirectToAction("Index", "Home");
            }
            ftr = new FundTransferReview
            {
                Balance = ba.Balance,
                FutureTransfer = "false",
            };
            return View(ftr);
        }
        //Receiving the transaction information
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> FundTransferReview(FundTransferReview ftr)
        {
            if (!ModelState.IsValid)
            {
                return View(ftr);
            }
            if(HttpContext.Session.GetString("NRIC")== null)
            {
                return RedirectToAction("Index", "Home");
            }
            Regex bankacc = new Regex(@"[0-9]{3}-[0-9]{6}-[0-9]{3}");
            BankUser bu;
            BankAccount ba;
            BankAccount senderAccount = bankAccountContext.GetBankAccount(HttpContext.Session.GetString("NRIC"));
            //Validation
            //Check if recipient exists
            if (bankacc.IsMatch(ftr.Recipient))
            {
                ba = bankAccountContext.GetBankAccount(ftr.Recipient);
                if (ba== null)
                {
                    ViewData["Message"] = "Bank account does not exists!";
                    return View(ftr);
                }
                bu = bankUserContext.GetBankUser(ba.Nric);
                if(bu == null)
                {
                    ViewData["Message"] = "Bank user does not exists!";
                }
            }
            else
            {
                bu = bankUserContext.GetBankUser(ftr.Recipient);
                if (bu != null)
                {
                    ba = bankAccountContext.GetBankAccount(bu.Nric);
                    if(ba == null)
                    {
                        ViewData["Message"] = "Bank account does not exists!";
                        return View(ftr);
                    }
                }
                else
                {
                    ViewData["Message"] = "Bank user does not exists!";
                    return View(ftr);
                }
                
            }
            
            if (transactionContext.ValidateTransactionLimit(senderAccount, ftr.TransferAmount) == false)
            {
                ViewData["Message"] = "Daily transfer limit reached!";
                return View(ftr);
            }
            // Check if Time of Transfer is not the day before
            if (ftr.TimeTransfer <= DateTime.Now)
            {
                ViewData["Message"] = "Future Transfer accepts date from tomorrow onwards!";
                return View(ftr);
            }
            // Check if recipient is sender
            if (bu.Nric == HttpContext.Session.GetString("NRIC"))
            {
                ViewData["Message"] = "You are not allowed to transfer to yourself";
                return View(ftr);
            }
            // Check if fundtransfer can be sent
            if (ftr.TransferAmount <= 0 || ftr.TransferAmount > senderAccount.Balance)
            {
                if (ftr.TransferAmount <= 0)
                {
                    ViewData["Message"] = "Unable to transfer zero dollars or less than zero dollars!";
                }
                else
                {
                    ViewData["Message"] = "Unable to transfer more than balance in account!";
                }

                return View(ftr);
            }
            //Check if FutureTransfer value is true and if time of transfer is empty.
            if (ftr.FutureTransfer == "true" && ftr.TimeTransfer == null)
            {
                ftr.FutureTransfer = "false";
            }
            
            TransferConfirmation tc;
            if (ftr.FutureTransfer == "true")
            {

                tc = new TransferConfirmation
                {
                    Recipient = bu.Name,
                    BankAccount = ba.AccNo,
                    TransferAmount = ftr.TransferAmount,
                    FutureTransfer = ftr.FutureTransfer,
                    TimeTransfer = ftr.TimeTransfer.Value.ToString(),
                };
                HttpContext.Session.SetInt32("transacID", 0);
            }
            else
            {
                // Create a record and post to Rest DB (done in JS)
                // Update Checkpoint 1
                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri("https://ocbcdatabase-0c55.restdb.io");
                client.DefaultRequestHeaders.Add("x-api-key", "61f2742d7e55272295017175");
                HttpResponseMessage response = await client.GetAsync("/rest/temptransac");
                HttpResponseMessage getResponse = await client.GetAsync("/rest/temptransac");
                if (response.IsSuccessStatusCode)
                {
                    string data = await response.Content.ReadAsStringAsync();
                    if (data != null)
                    {
                        List<TempTransac> tempTransacList = JsonConvert.DeserializeObject<List<TempTransac>>(data);
                        foreach (TempTransac tempTransac in tempTransacList)

PFD Challenge 1/Views/FundTransfer/Confirmation.cshtml
@*
    View for Transaction Confirmation
*@
@using Microsoft.AspNetCore.Http;
@section css{
    @*Add specific css script here*@
    <link rel="stylesheet" href="~/css/confirmation.css" />
}

@model PFD_Challenge_1.Models.TransferConfirmation

<div class="container" id="mainContainer2">
    <div class="first-container">
        <div style="text-align: center; margin-top:2%">
            <img id="imgLogo" src="~/images/FundTransfer.png"
                 style="width: 38%" />
            <h1 style="margin-top:4%">Review Transfer</h1>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col text-center">
            <form asp-action="Confirmation" style="text-align: center">
                <div class="container">
                    <div class="form-group form-check-inline" style="padding-top: 0px; padding-right: 115px; padding-left: 115px; display: inline-block;">
                        <div class="form-group" style="color: white">
                            <div class="to" style="padding-top: 2px;">
                                <div class="to" style="background-color: #AA1945; font-size: 20px;">To</div>
                            </div>
                            <div class="input" style="padding-top: 2px; padding-bottom: 0px; padding-right: 115px; padding-left: 115px; display: inline-block;">
                                <input asp-for="Recipient" type="text" readonly class="form-control" id="to" style="background-color: #ECDBBA; border: transparent; color: black; text-align: center; font-size: 25px;">
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-check-inline" style="padding-top: 0px; padding-right: 115px; padding-left: 115px; display: inline-block;">
                        <div class="form-group" style="color: white">
                            <div class="transferamount" style="padding-top: 2px;">
                                <div class="transferamount" style="background-color: #AA1945; font-size: 20px;">Transfer Amount</div>
                            </div>
                            <div class="input" style="padding-top: 2px; padding-bottom: 0px; padding-right: 115px; padding-left: 115px; display: inline-block;">
                                <input asp-for="TransferAmount" type="text" readonly class="form-control" id="transfer" style="background-color: #ECDBBA; border: transparent; color: black; text-align: center; font-size: 25px;">
                            </div>
                        </div>
                    </div>
                    <div>
                        <input hidden readonly asp-for="BankAccount" />
                        <input hidden readonly asp-for="FutureTransfer" />
                    </div>
                    @if (Model.FutureTransfer == "false")
                    {
                        <div id="futureTime">
                            <div class="form-group form-check-inline" style="padding-top: 0px; padding-right: 360px; padding-left: 180px; display: inline-block;">
                                <div class="form-group" style="color: white">
                                    <div class="plannedtimeoftransfer" style="padding-top: 2px;">
                                        <div class="plannedtimeoftransfer" style="background-color: #AA1945; font-size: 20px;">Planned time of transfer</div>
                                    </div>
                                    <div class="input" style="padding-top: 2px; padding-bottom: 0px; padding-right: 230px; padding-left: 230px; display: inline-block; font-size: 30px;">
                                        <div style="padding-top: 10px; padding-bottom: 10px; color: black;">Immediate</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div id="futureTime">
                            <div class="form-group form-check-inline" style="padding-top: 0px; padding-right: 360px; padding-left: 180px; display: inline-block;">
                                <div class="form-group" style="color: white; margin:auto auto auto 33px;">
                                    <div class="plannedtimeoftransfer" style="padding-top: 2px;">
                                        <div class="plannedtimeoftransfer" style="background-color: #AA1945; font-size: 20px;">Planned time of transfer</div>
                                    </div>
                                    <div style=" margin:auto;box-sizing: border-box; background-color: transparent; border: 2px solid white; border-radius: 0.6em; color: white; cursor: pointer; /*display: flex;*/ align-self: center; font-size: 1rem; font-weight: 400; line-height: 1; margin: 20px; padding: 1.2em 2.8em; text-decoration: none; text-align: center; text-transform: uppercase; font-family: 'Montserrat', sans-serif; font-weight: 700; padding-top: 2px; padding-bottom: 0px; padding-right: 130px; padding-left: 130px; display: inline-block;">
                                        <div style="padding-top: 10px; padding-bottom: 10px;">
                                            <div style="width: 300px; font-size: 25px;"><input asp-for="TimeTransfer" />@*@String.Format("{0:G}", Context.Session.GetString("TimeOfTransfer"))*@</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>

                <div class="every" style="padding-top: 0px; padding-right:50px;padding-left:50px; display: inline-block;">
                    <div><button action="submit" onclick="document.getElementById('id01').style.display='block'" style="width:auto;display: inline-block;" class="btn2">Confirm Transfer</button></div>
                </div>
                <div><div>Confirmation failed to send:</div><button id="FailSafe">Fail Confirm Demo Button</button></div>
                <div><div>Confirm Sent but fail to display transaction:</div><button id="FailSafe2">Demo Button</button></div>
            </form>
        </div>
    </div>
</div>


@section scripts{
    @*Add JavaScripts specifically for this view here*@
    <script src="~/js/confirmation.js"></script>
<script>
    $(document).ready(function () {
        const APIKEY = "61f2742d7e55272295017175";
        let restId = "@Context.Session.GetString("RestID")";
        let jsondata = {
            "checkpoint3": "True"
        };
        let settings = {
            "async": "true",
            "crossDomain": "true",
            "url": "https://ocbcdatabase-0c55.restdb.io/rest/temptransac/"+restId,
            "method": "PUT",
            "headers": {
                "content-type": "application/json",
                "x-apikey": APIKEY,
                "cache-control": "no-cache"
            },
            "processData": false,
            "data": JSON.stringify(jsondata)
        }

        $.ajax(settings).done(function (response) {
            console.log(response);
        });
        $("#FailSafe").click(function (e) {
            e.preventDefault()            
            alert("Internal Server Error 500!");
        })
    $("#FailSafe2").click(function (e) {
        e.preventDefault()
        let jsondata = {
            "checkpoint4": "True"
        };
        let settings = {
            "async": "true",
            "crossDomain": "true",
            "url": "https://ocbcdatabase-0c55.restdb.io/rest/temptransac/" + restId,
            "method": "PUT",
            "headers": {
                "content-type": "application/json",
                "x-apikey": APIKEY,
                "cache-control": "no-cache"
            },
            "processData": false,
            "data": JSON.stringify(jsondata)
        }
        $.ajax(settings).done(function (response) {
            console.log(response);
        });
        alert("Internal Server Error 500!");
    })
    })
</script>
}

PFD Challenge 1/Views/FundTransfer/Failure.cshtml
@{
    ViewData["Title"] = "Failed";
}

@*ViewData message is the error message*@
<div style="text-align: center; margin-top: 2%;">
    <h3>Reason: @ViewData["Message"]</h3>
</div>

<div style="margin-top:2%;">
    <img id="imgLogo" src="~/images/Failure Page – 2.png"
         style=" width: 100%; height: auto;" />
</div>

PFD Challenge 1/Views/FundTransfer/FundTransfer.cshtml
@*
    *Main page for transfer
    Remember to declare model used
*@

@model PFD_Challenge_1.Models.FundTransferVM

@section css{
    @*Add specific css script here*@
    <link rel="stylesheet" href="~/css/futuretransfer.css" />
}
<div class="container" id="mainContainer2">
    <div class="first-container">
        <div style="text-align: center; margin-top:5%;">
            <img id="imgLogo" src="~/images/FundTransfer.png"
                 style="width: 30%" />
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col text-center">
            <div class="container">
                <form>
                    <div class="form-group" style="color: #BA2B43; margin-top: 5%; margin-bottom: 5%;">
                        <h2>Greetings, @ViewData["User"]</h2>
                    </div>
                    <div class="form-group" style="color: black; font-family: 'Rampart One', cursive; margin-bottom: 0% ">
                        <h4><label for="balance">What you have (SGD)</label></h4>
                    </div>
                    <div class="form-group" style="color: #2D4263;">
                        <div class="input" style="padding-top: 20px; padding-bottom: 20px; padding-right: 140px; padding-left: 140px; display: inline-block; color: black; border-color: white; ">@Html.DisplayFor(model => model.account.Balance)</div>
                    </div>
                    <div class="form-group" style="color: black; font-family: 'Rampart One', cursive; margin-bottom: 0% ">
                        <h4><label for="activity">Your activity</label></h4>
                    </div>
                    <div class="form-group" style="color: #2D4263;">
                        <div class="input" style="padding-top: 20px; padding-bottom: 20px; padding-right: 20px; padding-left: 20px; display: inline-block; color: black; border-color: white; ">
                            @{ if (Model.transactions.Amount == 0)
                                {
                                    <div>No transactions</div>
                                }
                                else
                                {
                                    <div><span>@Html.DisplayFor(model => model.transactions.TimeTransfer)</span>   Transfer: $<span>@Html.DisplayFor(model => model.transactions.Amount)</span></div>
                                }

                            }
                        </div>
                    </div>
                </form>
            </div>
            <!-- Login Button -->
            <div class="every" style="padding-right:50px;padding-left:50px; display: inline-block;">
                <div class="btn">@Html.ActionLink("Make a Transfer", "FundTransferReview", "FundTransfer")</div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    @*Add JavaScripts specifically for this view here*@
    <script src="~/js/futuretransfer.js"></script>
}

PFD Challenge 1/Views/FundTransfer/Success.cshtml
@{
    ViewData["Title"] = "Success Notification";
}

<div style="margin-top:2%;">
    <img id="imgLogo" src="~/images/Success Page – 2.png"
         style=" width: 100%; height: auto;" />
</div>